### ISSUE TITLE
not enough info for install

### ISSUE THREAD

**Issue by Soldierofthelam** [ImpulseFPS/qb-personalcrafting#1]
no image
no table info for shared list
no information in readme where to put readme info
 little info provided 

Updated:
Managed to get the table to function After tweaking but if you move or bump into the  table it dissolved into the ground also when removing the table it deletes the table not adds item back to inventory.

**Comment by ImpulseFPS** [comment]
i didnt provide an image for the item because i dont have it lmao
Now if you cant copy past the item and just rename it into "table" thats on you
what do you mean there is no info where to put the read me readme is the config...
little info provided? i made the script all the important things are in the config 

table dissolving is prop issue not a script issue so yea if you want the table not to dissolve when bumping into it just put another prop for the table...

and the script is legit drag and drop edit the config and make an item... now if you cant do that im sorry im not here to teach you or to make it easy for people to use everyone who has any coding experience can setup the script with easy so yea...

**Comment by Soldierofthelam** [comment]
Thankfully I know lua and got it working as stated,
problem is no matter what prop you use,  so no your solution to change the prop is not right!
if you bump into the prop it dissolves into the floor which it is related to the script and progress bar no reading 




https://streamable.com/35ffqy

**Comment by ImpulseFPS** [comment]
So watched the clip and no that is 100% not a script problem one script is not controling the prop after its being placed on the ground that being said this issue never existed before the prop table used has more props on the table original so those props would fall off because the prop is not made to be static this issue you are having i have never encountered it before 

Simply because the script is not longer in control of the prop after its placed

**Comment by Soldierofthelam** [comment]
Interesting,
   So if the script is no longer in control of the prop and it doesn't place as a static item wouldn't that mean I wouldn't be able to access the menu on it with target menu?
 You can still access the prop whether it be the one you used in the script or the one I replaced it just doesn't read as static.
Which is odd cause my other table script doesn't have this issue.

**Comment by ImpulseFPS** [comment]
i dont know what to tell you because i have downloaded the  and updated the hole server to the new version checkd for the issue you have and i dont have it..
